#!/bin/bash
#
# Usage: $0 <input dir> <output dir>

set -e

. "$(dirname "$0")/lib.sh"

usage() {
    cat << EOF
    $(basename "$0") path/to/artist path/to/destination
EOF
}

[ $# -lt 1 ] && usage && exit 1

# artist
#  => respect basename of target, in case pwd been used as input/$1
artist=$(basename "$2")
# special artist name
[ "$artist" = '群星' ] && unset artist
# remove comments
IFS='()（）' read -r artist _ <<< "$artist"

# find obsolute(s)
for album in "$2"/*; do
    [ -e "$1/$(basename "$album")" ] || {
        echo "=== remove outdated album $album"
        [ "$RUN" -ne 0 ] && rm -rfv "$album"
    }
done

#WIDTH=$(find "$1" -maxdepth 1 | wc -L)
#WIDTH=$(($WIDTH - $(wc -L <<< "$1") + 5))

# list albums 
for album in "$1/"*; do
    [ -e "$album/ignore" ] && echo "=== ignore album $album" && continue

    name="$(basename "$album")"

    if which tput &> /dev/null; then
        echo -ne ">>> $name"
        tput hpa "$WIDTH"
        echo -ne "==> $2/$name\n"
    else
        echo -e ">>> $name ==> $2/$name"
    fi

    ARTIST="$artist" "$(dirname "$0")"/update-album.sh "$album" "$2/$name"
done
